### PR TITLE
Regenerate client with fixed swagger

### PR DESCRIPTION
**Pull request by aethanol**
This PR regenerates the client with an adapted generator based off of https://github.com/grafeas/client-go/pull/15.
The current client is not up to date, and has old bugs that were fixed in the past year or so.
This PR also moves to go module using name `module github.com/grafeas/client-go`, and moves away from keeping the version in the generated directory.
Now we generate into two paths, `grafeas` and `projects` for the two different swagger files. Updating documentation included in README.md

### CODE REVIEW

**Comment by aethanol** [comment]
Hey @wkozlik , just tagging you here for visibility.

**Comment by aethanol** [comment]
Turns out this is being affected by a bug in swagger-codegen, looking into a fix.

**Review by wkozlik — APPROVED** [review]
Thank you for this contribution. This looks great!

**Comment by aethanol** [comment]
Thanks for reviewing @wkozlik ! Would you be able to tag a version when you get a chance as well? I have it as `1.0.0` in the config.go.json file.
Otherwise this should be good to go. I'll plan on updating this PR whenever the swagger-codegen change gets merged.

**Comment by wkozlik** [comment]
Thank you for this fix. It is looking great. I need to update the build step, to be able to merge this PR.

**Comment by aethanol** [comment]
@wkozlik anything I can help contribute to?

**Comment by wkozlik** [comment]
I am sorry for the delay. We should be okay now. Could you resolve merge conflicts?

**Pull request merged**
